# Generated by Django 4.2.2 on 2023-06-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image1_post_image2_post_image3_post_image4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
